---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mk-raif-disk
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: "ext4" 
    pdName: "mk-raif-disk"
